before_script:
  - apt update

pages:
  script:
  - apt install -y python3 python3-pip
  - pip3 install mkdocs
  - pip3 install mkdocs-material
  - mkdir .docs
  - mv * .docs
  - mv {.,}docs
  - mkdocs build
  - mv site public
  artifacts:
    paths:
      - public

pdf:
  image: aergus/latex
  script: 
  - latexmk -pdf main.text
  - mv main.pdf tfm.pdf
  artifacts:
    paths:
    - tfm.pdf

